name: Deploy Lambda

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the TypeScript code
      - name: Build project
        run: npm run build

      # Step 5: Create the output directory
      - name: Create output directory
        run: mkdir -p dist

      # Step 6: Package the code for deployment
      - name: Package Lambda
        run: zip -j dist/handler.zip dist/index.js

      # Step 7: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      # Step 8: Deploy to AWS Lambda using AWS CLI
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name my-typescript-lambda \
            --zip-file fileb://dist/handler.zip \
            --publish
